### ISSUE TITLE
Fork with TypeScript support

### ISSUE THREAD

**Issue by leonardmq** [hyvor/hyvor-talk-react#4]
Hi there,

I was unable to use this package because the dependencies are too old, and it does not have TypeScript support. 

I rewrote the repo in TypeScript and also added a flag (`isMounted`) on the components to make them only render client-side and not SSR (I am using Next.js). I just went off your `propTypes` definitions to define the TypeScript types, so that could be made cleaner.

Feel free to do whatever you want with it:
- https://github.com/leonardmq/hyvor-talk-react-typescript
- https://www.npmjs.com/package/hyvor-talk-react-typescript

**Comment by supunkavinda** [comment]
Hello @leonardmq 

Thank you very much for your awesome work.

We are re-writing this main library with Typescript support and adding new missing params, and cleaning up the codebase.

May I ask, why did you add logic to only render on the client-side? What happens if it is rendered on the server side? (I have 0 experience with SSR, so just trying to figure out it is needed in the main package).

**Comment by leonardmq** [comment]
Hey @supunkavinda 

Cool, happy to hear you will be officially supporting TypeScript!

> May I ask, why did you add logic to only render on the client-side? What happens if it is rendered on the server side? (I have 0 experience with SSR, so just trying to figure out it is needed in the main package).

The `mounted` flag was not actually needed (I was tired!) since all the `window` related logic is already happening inside `useEffect`, which only runs client-side. 

For frameworks such as Next.js, referring to `window` while server-side causes an error because the server does not have a `window`. The way people usually solve that is by doing their `window` related code inside a `useEffect` hook because `useEffect` runs only client-side; or by adding conditionals to check whether `window` exists or not.

I've also used more problematic packages in the past where `window` is being used somewhere during the import such that merely doing `import XXXX from "XXXX"` is enough to cause an error server-side. In such cases, people use dynamic imports to run the import only client-side. 

This article gives a good breakdown of the `window` related problems that often come up: [https://dev.to/vvo/how-to-solve-window-is-not-defined-errors-in-react-and-next-js-5f97](https://dev.to/vvo/how-to-solve-window-is-not-defined-errors-in-react-and-next-js-5f97)
